// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "student.hpp" // student implementations
// tests for exercise 1
TEST_CASE("Ex1", "[example]")
{
    REQUIRE(Hello, World);
}

